___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Series, Session - 3</p><h1>

## Creating a Pandas Series

In [2]:
import numpy as np
import pandas as pd

### Creating a Pandas Series with Basic Format

In [6]:
np.array([1,2,3, 1.1])

array([1. , 2. , 3. , 1.1])

### Creating Pandas Series by Using a ``list``, numpy array or ``dict``ionary

In [4]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

### **Using NumPy Arrays**

### **Using Dictionary**

### Using Scalar Value

In [3]:
pd.Series("Steve")

0    Steve
dtype: object

In [4]:
pd.Series("Steve",index=range(3))

0    Steve
1    Steve
2    Steve
dtype: object

In [7]:
pd.Series(10,index=[1,2])

1    10
2    10
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [8]:
set1=(1,2,3,6)

In [33]:
ser=pd.Series(set1, index=['a','b','c','d'])

In [11]:
pd.Series(list)

0    <class 'list'>
dtype: object

In [12]:
pd.Series([set,list,len])

0              <class 'set'>
1             <class 'list'>
2    <built-in function len>
dtype: object

In [20]:
pd.Series([set,print('Matthew'),len])

Matthew


0              <class 'set'>
1                       None
2    <built-in function len>
dtype: object

In [28]:
mix_data=['Steve',2,True,[1,2,3],(2,3)]
mix_data

['Steve', 2, True, [1, 2, 3], (2, 3)]

In [29]:
pd.Series(mix_data , index=(3,5,7,9,2))[9]

[1, 2, 3]

In [30]:
np.array(mix_data)

C:\Users\49159\AppData\Local\Temp/ipykernel_44044/1134927132.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(mix_data)


array(['Steve', 2, True, list([1, 2, 3]), (2, 3)], dtype=object)

### Basic Attributes of Series

In [34]:
type(ser)

pandas.core.series.Series

In [35]:
ser.dtype

dtype('int64')

In [36]:
ser.ndim

1

In [37]:
ser.shape

(4,)

In [39]:
ser.size

4

In [40]:
ser.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [41]:
ser.keys

<bound method Series.keys of a    1
b    2
c    3
d    6
dtype: int64>

In [52]:
ser.values

array([1, 2, 3, 6], dtype=int64)

In [48]:
[i for i in ser.values]

[1, 2, 3, 6]

In [54]:
list(ser.items())

[('a', 1), ('b', 2), ('c', 3), ('d', 6)]

In [62]:
list(ser.items())[1:3]

[('b', 2), ('c', 3)]

In [64]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])
ser

c     8
b     9
a    10
e    10
f     2
d     8
g    20
i    22
h    13
j    23
dtype: int32

In [66]:
ser.head()

c     8
b     9
a    10
e    10
f     2
dtype: int32

In [67]:
ser.tail()

d     8
g    20
i    22
h    13
j    23
dtype: int32

In [74]:
ser.sample(2)

h    13
g    20
dtype: int32

In [77]:
ser.sort_index(ascending=False)

j    23
i    22
h    13
g    20
f     2
e    10
d     8
c     8
b     9
a    10
dtype: int32

In [78]:
ser.sort_values()

f     2
c     8
d     8
b     9
a    10
e    10
h    13
g    20
i    22
j    23
dtype: int32

In [89]:
ser.searchsorted(['a'])

array([10], dtype=int64)

In [90]:
ser.isin([2,5,6])

c    False
b    False
a    False
e    False
f     True
d    False
g    False
i    False
h    False
j    False
dtype: bool

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [91]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])

In [92]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [107]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [98]:
ser1.sort_index()

1

In [101]:
ser2.sort_values()['Germany']

2

In [104]:
ser1.sort_index[2]

TypeError: 'method' object is not subscriptable

In [108]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [109]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [110]:
panser['terry']

121

### pandas_series[index] | pandas_series[[indices, indices...]]

In [111]:
ind1=['terry', 'micheal', 'orion']

In [112]:
panser[ind1]

terry      121
micheal    200
orion      150
dtype: int64

In [113]:
ind1[::-1]

['orion', 'micheal', 'terry']

<h1><p style="text-align: center;">Pandas DataFrames, Session - 3</p><h1>

In [114]:
data = [1,2,39,67,90]
data

[1, 2, 39, 67, 90]

In [127]:
pd.DataFrame(data, index=(1,2,3,4,5),columns=['Sayilar'])

Sayilar
1        1
2        2
3       39
4       67
5       90

In [129]:
data2=np.arange(1,10).reshape(3,3)
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
pd.DataFrame(data2, columns=['var1','var2','var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [139]:
data3= np.arange(1,17).reshape(4,4)
data3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [145]:
df=pd.DataFrame(data3,columns=['var1','var2','var3','var4'] )

In [147]:
df.head(2)

var1  var2  var3  var4
0     1     2     3     4
1     5     6     7     8

In [153]:
df.sample(2)

var1  var2  var3  var4
1     5     6     7     8
2     9    10    11    12

In [162]:
df.columns[0:]

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [166]:
len(df)

4

In [183]:
ali=pd.read_csv('data.csv', encoding= 'unicode_escape')
ali

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[541909 rows x 8 columns]

'c:\\Users\\49159\\Downloads'

### Recap for Several Selecting Attributes

for your info:

* 1 dim --> vector 
* 2 dim --> matrix
* 3 dim --> tensor

In [184]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [187]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [189]:
panser.index

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [190]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [192]:
list(panser.items())


[('terry', 121), ('micheal', 200), ('orion', 150), ('jason', 99)]

In [199]:
panser.isin(['terry'])

terry      False
micheal    False
orion      False
jason      False
dtype: bool

In [206]:
panser.index.isin(['terry'])

array([ True, False, False, False])

In [211]:
[panser < 100 & panser > 91]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [214]:
ali.corr('Quantity','Unit Price')

ValueError: method must be either 'pearson', 'spearman', 'kendall', or a callable, 'Quantity' was supplied