___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 2 (Part - 2)</p><h1>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [4]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [15]:
type(arr[0])

numpy.int32

In [16]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [19]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[1,:2]

array([20, 25])

In [31]:
arr_2d[1][:2]

array([20, 25])

In [32]:
arr_2d[1,1]=111

In [34]:
arr_2d_copy=arr_2d.copy()

In [35]:
arr_2d_copy

array([[  5,  10,  15],
       [ 20, 111,  30],
       [ 35,  40,  45]])

In [36]:
arr_2d_copy[1,1]=27

In [38]:
arr_2d

array([[  5,  10,  15],
       [ 20, 111,  30],
       [ 35,  40,  45]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [40]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [45]:
index_list=[1,3,7]
v[index_list]

array([ 3,  9, 21])

In [69]:
arr2d=np.zeros((10,10),dtype=int)
arr2d[:]=np.arange(0,10,1)
arr2d.T

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [58]:
k=[2,4,6,8]

In [59]:
arr2d[k]


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

<h3>any_array[[row indices], [column indices]]</h3>

In [62]:
jj=np.arange(1,17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [68]:
jj[[0,2,3],[0,1,3]]

array([ 1, 10, 16])

### Using ***basic index*** and ***fancy index*** together

In [74]:
jj[1, [1,3]]

array([6, 8])

### Using ***basic slicing*** and ***fancy index*** together

In [70]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [72]:
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [73]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

# Selection on a Condition

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [95]:
arr=np.arange(1,11)

In [77]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [78]:
bool_arr = arr > 4

In [79]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [84]:
arr[(arr!=3) & (arr!=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

https://numpy.org/doc/stable/user/theory.broadcasting.html

In [91]:
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [87]:
arr[:5]=77
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [88]:
a=[0,2,4,6,8,10]

In [89]:
a[0:3]=[100,100,90]

In [90]:
a

[100, 100, 90, 6, 8, 10]

In [100]:
arrs=arr.copy()

In [101]:
arrs[:3]=[10,11,12]

In [102]:
arrs

array([10, 11, 12,  4,  5,  6,  7,  8,  9, 10])

In [103]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [104]:
import numpy as np
arr = np.arange(0,10)

In [108]:
arr*[3,2,2,4,5,6,7,8,9,0]

array([ 0,  2,  4, 12, 20, 30, 42, 56, 72,  0])

In [112]:
import warnings
warnings.filterwarnings('ignore')

In [114]:
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [115]:
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [116]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [118]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [125]:
np.max(arr)

9

In [126]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [131]:
np.quantile(arr,0)

0

In [136]:
np.subtract(v,52)

array([-52, -49, -46, -43, -40, -37, -34, -31, -28, -25])

In [139]:
np.power(arr,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [122]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## Statistical Calculations

In [140]:
arr.mean()

4.5

In [141]:
arr.sum()

45

In [143]:
stats.mode()

NameError: name 'stats' is not defined

In [145]:
a=np.array([[0,1,6],[2,4,1]])
a

array([[0, 1, 6],
       [2, 4, 1]])

In [153]:
np.max(a,axis=1)[0]

6

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``arr.corrcoef()`` | Returns correlation coefficient of array

# The End of the Session - 2

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.